### PR TITLE
Do not use already imported in engine libraries while cleaning up

### LINKED ISSUE #247: Problem with DotNetty
## Description
1. There should be a option to treat api compatibility level .net 4.x as .net standard 2.0. Because the .net 4.x is modified by Unity. It can be compatible with .net standard assemblies.
2. The dependencies of DotNetty is not installed. When I choose the 5 packages in red rectangles. The dependencies below should be installed.

image

- **NuGet Package:** DotNetty
- **NuGetForUnity Version:** 1.0.4
- **Unity Version:** 2019.1.0f2
- **Operating System:** Windows

### LINKED ISSUE #320: some packages will download a bunch of System.* reference
add Protobuf-net assembly to nuget.
the NugetForUnity dll will download 92 System.* packages, which clashes with those from unity.

- **NuGet Package:** Protobuf-net
- **NuGetForUnity Version:** 2.0
- **Unity Version:** 2019.2.15f1
- **Operating System:** windows 10 pro

### LINKED ISSUE #322: nuget versions not match
2PW9WI4Z{5SRAGCI(B5@F0G
unity debug console:
Assembly 'Assets/Packages/System.IO.Pipelines.4.6.0/lib/netstandard2.0/System.IO.Pipelines.dll' will not be loaded due to errors:
System.IO.Pipelines references strong named System.Buffers, versions has to match. Assembly references: 4.0.2.0 Found in project: 4.0.3.0.

Unity nuget version does not match, but nuget for unit downloaded. What should I do?

### LINKED ISSUE #330: By default NuGetForUnity downloads dozens of unneeded "sytem" packages, causing duplication compilation errors for NSubstitute.
## Description
If you download in a fresh Unity Project + NuGetForUnity then try to install NSubstitute nuget (versions below), then dozens of packages are installed with names like "System.Dynamic.Runtime.4.30" and "System.IO.4.3.0" and "runtime.debian.8-x64.runtime.native.System.Security.Cryptogrophay.OpenSsl.4.3.0". On and on.

NSubstitute should really just have Castle.Core.4.4.0 and System.Threading.Tasks.Extensions.4.3.0. In fact, after NuGetForUnity downloads all these extra packages, NuGet->Show Dependecy Tree does show only these. However in Nuget->Manage  Nuget Packages, all these extra packages are listed.

These extra unneeded packages then permanently cause the Project Build to fail building with error:
error CS1703: Multiple assemblies with equivalent identity have been imported: 

Then goes on to list various DLLs conflicted from the various .\Assets\Packages subdirectories.

## Versions
NSubstitute 4.2.1
NuGetForUnity 2.0.0
Unity 2020.2.0a10.1205 . Also tried this with Unity 2019.3.13.f1
Windows 10x64
All "options" for Unity/NuGetForUnity used here are essentially at default after creating new Unity Project.

### LINKED ISSUE #336: Multiple assemblies with equivalent identity have been imported
## Description

When installing Stripe through NuGetForUnity it also installs a bunch of System.XXX in packages, which results in the following error: 

> Microsoft (R) Visual C# Compiler version 2.9.1.65535 (9d34608e)
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> error CS1703: Multiple assemblies with equivalent identity have been imported

If I delete manually those directories, unity eventually re-download again those dll's :S

- **NuGet Package:** Stripe.net 37.20.0
- **NuGetForUnity Version:** 2.0.1
- **Unity Version:** 2019.3.13f1
- **Operating System:** Windows 10

### LINKED ISSUE #343: Downloading the CsvHelper package result in a conflict with Microsoft.CSharp.dll when targeting NetStandard 2.0
## Description

Downloading the CsvHelper package will download Microsoft.CSharp.4.5.0, which result in a conflict :

> Microsoft (R) Visual C# Compiler version 2.9.1.65535 (9d34608e)
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> error CS1703: Multiple assemblies with equivalent identity have been imported: 'C:\Users\Developpeur\Documents\Source\Projets\Socotec2_Unity\Assets\Packages\Microsoft.CSharp.4.5.0\lib\netstandard2.0\Microsoft.CSharp.dll' and 'C:\Program Files\Unity\Hub\Editor\2019.4.10f1\Editor\Data\MonoBleedingEdge\lib\mono\4.7.1-api\Microsoft.CSharp.dll'. Remove one of the duplicate references.

- **NuGet Package:** CsvHelper 15.0.5
- **NuGetForUnity Version:** 2.0.1
- **Unity Version:** 2019.4.10f1
- **Operating System:** Windows 10

### LINKED ISSUE #354: Nuget for Unity installs too many packages
## Description
Nuget for Unity installs too many packages. Aside from the package I want to install, it also installs packages from the System namespace (like System.IO, System.Linq, System.Collections, etc.), which should not be installed, because obviously those DLLs are already present.

Because of the installation of those additional DLLs, Unity complains about "Multiple assemblies with equivalent identity".

The full content of the packages.config file after I installed only the one package mentioned below:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Castle.Core" version="4.4.0" />
  <package id="Microsoft.NETCore.Platforms" version="1.1.0" />
  <package id="Microsoft.NETCore.Targets" version="1.1.0" />
  <package id="Microsoft.Win32.Primitives" version="4.3.0" />
  <package id="Moq" version="4.15.1" />
  <package id="NETStandard.Library" version="1.6.1" />
  <package id="runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.native.System" version="4.3.0" />
  <package id="runtime.native.System.IO.Compression" version="4.3.0" />
  <package id="runtime.native.System.Net.Http" version="4.3.0" />
  <package id="runtime.native.System.Security.Cryptography.Apple" version="4.3.0" />
  <package id="runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple" version="4.3.0" />
  <package id="runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="System.AppContext" version="4.3.0" />
  <package id="System.Buffers" version="4.3.0" />
  <package id="System.Collections" version="4.3.0" />
  <package id="System.Collections.Concurrent" version="4.3.0" />
  <package id="System.Collections.NonGeneric" version="4.3.0" />
  <package id="System.Collections.Specialized" version="4.3.0" />
  <package id="System.ComponentModel" version="4.3.0" />
  <package id="System.ComponentModel.Primitives" version="4.3.0" />
  <package id="System.ComponentModel.TypeConverter" version="4.3.0" />
  <package id="System.Console" version="4.3.0" />
  <package id="System.Diagnostics.Debug" version="4.3.0" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.3.0" />
  <package id="System.Diagnostics.Tools" version="4.3.0" />
  <package id="System.Diagnostics.TraceSource" version="4.3.0" />
  <package id="System.Diagnostics.Tracing" version="4.3.0" />
  <package id="System.Dynamic.Runtime" version="4.3.0" />
  <package id="System.Globalization" version="4.3.0" />
  <package id="System.Globalization.Calendars" version="4.3.0" />
  <package id="System.Globalization.Extensions" version="4.3.0" />
  <package id="System.IO" version="4.3.0" />
  <package id="System.IO.Compression" version="4.3.0" />
  <package id="System.IO.Compression.ZipFile" version="4.3.0" />
  <package id="System.IO.FileSystem" version="4.3.0" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" />
  <package id="System.Linq" version="4.3.0" />
  <package id="System.Linq.Expressions" version="4.3.0" />
  <package id="System.Net.Http" version="4.3.0" />
  <package id="System.Net.Primitives" version="4.3.0" />
  <package id="System.Net.Sockets" version="4.3.0" />
  <package id="System.ObjectModel" version="4.3.0" />
  <package id="System.Reflection" version="4.3.0" />
  <package id="System.Reflection.Emit" version="4.3.0" />
  <package id="System.Reflection.Emit.ILGeneration" version="4.3.0" />
  <package id="System.Reflection.Emit.Lightweight" version="4.3.0" />
  <package id="System.Reflection.Extensions" version="4.3.0" />
  <package id="System.Reflection.Primitives" version="4.3.0" />
  <package id="System.Reflection.TypeExtensions" version="4.3.0" />
  <package id="System.Resources.ResourceManager" version="4.3.0" />
  <package id="System.Runtime" version="4.3.0" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.5.0" />
  <package id="System.Runtime.Extensions" version="4.3.0" />
  <package id="System.Runtime.Handles" version="4.3.0" />
  <package id="System.Runtime.InteropServices" version="4.3.0" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" />
  <package id="System.Runtime.Numerics" version="4.3.0" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.0" />
  <package id="System.Security.Cryptography.Cng" version="4.3.0" />
  <package id="System.Security.Cryptography.Csp" version="4.3.0" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" />
  <package id="System.Security.Cryptography.OpenSsl" version="4.3.0" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" />
  <package id="System.Text.Encoding" version="4.3.0" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" />
  <package id="System.Text.RegularExpressions" version="4.3.0" />
  <package id="System.Threading" version="4.3.0" />
  <package id="System.Threading.Tasks" version="4.3.0" />
  <package id="System.Threading.Tasks.Extensions" version="4.5.1" />
  <package id="System.Threading.Timer" version="4.3.0" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" />
  <package id="System.Xml.XDocument" version="4.3.0" />
  <package id="System.Xml.XmlDocument" version="4.3.0" />
</packages>
```

- **NuGet Package:** Moq, 4.15.1
- **NuGetForUnity Version:** 2.0.0
- **Unity Version:** 2020.1.6f1
- **Operating System:** Win 10, 64 bit

### PR DESCRIPTION
**Pull request by KonH**
Refers to https://github.com/GlitchEnzo/NuGetForUnity/issues/354

Fixes #354
Fixes #343 
Fixes #247
Fixes #320 
Fixes #322 
Fixes #330 
Fixes #336

### CODE REVIEW

File: Assets/NuGet/Editor/NugetHelper.cs [hunk 1]
```diff
@@ -542,6 +543,46 @@ private static void Clean(NugetPackageIdentifier package)
...
+
+        private static string[] GetAllLookupPaths() {
+            var executablePath = EditorApplication.applicationPath;
+            var roots = new[] {
+                // MacOS directory layout
+                Path.Combine(executablePath, "Contents"),
+                // Windows directory layout
+                Path.Combine(Directory.GetParent(executablePath).FullName, "Data")
+            };
+            var relativePaths = new[] {
```
Comment (jwittner) [inline Assets/NuGet/Editor/NugetHelper.cs:572]: We should be able to select the right paths here based on the scripting backend settings, e.g. MonoBleedingEdge if we're targeting .Net 4.x and NetStandard if we're setup for .Net Standard.

**Review by jwittner — CHANGES_REQUESTED** [review]
Looking really good, still need to test it out though. Just the one comment below on selecting the right path based on the Unity setting around scripting.

File: Assets/NuGet/Editor/NugetHelper.cs [hunk 2]
```diff
@@ -542,6 +543,46 @@ private static void Clean(NugetPackageIdentifier package)
             }
         }
 
+        private static bool IsAlreadyImportedInEngine(NugetPackageIdentifier package) {
+            var alreadyImportedLibs = GetAlreadyImportedLibs();
+            var isAlreadyImported = alreadyImportedLibs.Contains(package.Id);
```
Comment (jwittner) [inline Assets/NuGet/Editor/NugetHelper.cs:548]: Thinking about this more, I'm wondering if this is the right level to do this. There's nothing preventing multiple assemblies being packaged in a given Nuget package. I think the more bullet proof solution would be to install the package, then check all the assemblies that have been in stalled in the package, and remove just the targeted ones.

**Review by jwittner — CHANGES_REQUESTED** [review]

File: Assets/NuGet/Editor/NugetHelper.cs (hunk 1 above)
Comment (jwittner) [reply Assets/NuGet/Editor/NugetHelper.cs:572]: Oh, I see your comment on the related issue that MonoBleedingEdge was still being leveraged when targeting .Net Standard. Hmmm.

File: Assets/NuGet/Editor/NugetHelper.cs (hunk 2 above)
Comment (jwittner) [reply Assets/NuGet/Editor/NugetHelper.cs:548]: I'm supposing that practically this might not be the case for any of the "system" packages that we're solving for here - in which case I'm a fan of this early out. We'll need to test this out against the many different packages that have reported the issue this is solving, and if we don't run into any problems I'm definitely down to start with this implementation. =)

**Comment by jwittner** [comment]
I went through the existing issues that are likely related to this and tagged them so we can test them out with this fix.

**Comment by KonH** [comment]
@jwittner thanks for the feedback!
I tested linked issues in my environment and it looks fine (only one has the same behavior - https://github.com/GlitchEnzo/NuGetForUnity/issues/345, but I think it related to some other issue), comments added.
What do I need to do as a next step for now?

**Comment by jwittner** [comment]
Thanks for the diligent testing @KonH ! Sorry for the delay on this, wrapping up a project this week for a customer. Gonna pull these changes down and do some local testing.

File: Assets/NuGet/Editor/NugetHelper.cs [hunk 3]
```diff
@@ -542,6 +543,46 @@ private static void Clean(NugetPackageIdentifier package)
...
+            return isAlreadyImported;
+        }
+
+        private static HashSet<string> GetAlreadyImportedLibs() {
+            var lookupPaths = GetAllLookupPaths();
+            var libNames = lookupPaths
+                .SelectMany(directory => Directory.EnumerateFiles(directory, "*.dll", SearchOption.AllDirectories))
+                .Select(Path.GetFileName)
+                .Select(p => Path.ChangeExtension(p, null));
+            var result = new HashSet<string>(libNames);
```
Comment (jwittner) [inline Assets/NuGet/Editor/NugetHelper.cs:559]: I think we can safely cache this. I'm seeing roughly 1/3 of a second per call to this method, which if there's a big dependency chain, can add up.

**Review by jwittner — CHANGES_REQUESTED** [review]
Couple changes left and I think this is good, it was working well for me. I've made the changes and created a PR into your branch here: https://github.com/KonH/NuGetForUnity/pull/1

Once you review that and we get it merged I can resolve these comments and merge this into master. Great work!!!

**Comment by KonH** [comment]
Thanks, completely agree with your changes.
